/************************************************/
/* USE ONLY TO TEST LINKING AGAINST libFireBird */
/* CHECKS ALL libFireBird FUNCTIONS             */
/************************************************/

#include "tap.h"
#include "../av/FBLib_av.h"
#include "../flash/FBLib_flash.h"
#include "../hdd/FBLib_hdd.h"
#include "../ini/FBLib_ini.h"
#include "../libFireBird.h"
#include "../main/FBLib_main.h"
#include "../rec/FBLib_rec.h"
#include "../shutdown/FBLib_shutdown.h"
#include "../string/FBLib_string.h"
#include "../tap/FBLib_tap.h"
#include "../tapcom/FBLib_tapcom.h"

TAP_ID(0);
TAP_PROGRAM_NAME("");
TAP_AUTHOR_NAME("");
TAP_DESCRIPTION("");
TAP_ETCINFO(__DATE__);


dword TAP_EventHandler (word event, dword param1, dword param2)
{
  (void) event;
  (void) param2;

  return param1;
}


int TAP_Main (void)
{
  AddSec(0, 0, 0);
  AddTime(0, 0);
  AudioTrackInfo();
  BMP_WriteHeader(NULL, 0, 0);
  BootReason();
  CallTraceComment(NULL);
  CallTraceEnable(FALSE);
  CallTraceEnter(NULL);
  CallTraceExit(NULL);
  CallTraceExitResult(NULL, NULL);
  CallTraceInit();
  CaptureScreen(0, 0, NULL, FALSE, 0);
  ChangeDirRoot();
  CharToISO(NULL);
  CharToUTF8(NULL);
  CompressBlock(NULL, 0, NULL);
  CompressedTFDSize(NULL, 0, NULL);
  CompressTFD(NULL, 0, NULL, 0, 0, NULL);
  CRC16(0, NULL, 0);
  CRC32(0, NULL, 0);
  DayOfWeek(0);
  Delay(0);
  DrawOSDLine(0, 0, 0, 0, 0, 0);
  DumpMemory(NULL, 0, 0);
  ELFCleanup();
  ELFGetSectionAddress(0, NULL, NULL);
  ELFGetSectionIndex(NULL);
  ELFOpenAbsFile(NULL);
  ELFOpenFile(NULL);
  ELFReadData(0, NULL);
  ELFReadDWORD(0, NULL);
  ELFReadELFHeader();
  ELFReadSectionHeaders();
  ELFReadShstrtabSection();
  EndMessageWin();
  ExtractLine(NULL, NULL);
  FindGotPointer(0);
  FirmwareDatMJD();
  FIS_fwAppl_ClrTimer();
  FIS_fwAppl_ExecProgram();
  FIS_fwAppl_ExportChData();
  FIS_fwAppl_ImportChData();
  FIS_fwAppl_RestartTimeShiftSvc();
  FIS_fwAppl_ShoutCast();
  FIS_fwAppl_StartTempRec();
  FIS_fwAppl_StopPlaying();
  FIS_fwAppl_StopTempRec();
  FIS_fwAppl_WaitEvt();
  FIS_fwApplChannel_GetAgc();
  FIS_fwApplChannel_GetBer();
  FIS_fwApplHdd_FileCutPaste();
  FIS_fwApplHdd_GetFileInfo();
  FIS_fwApplHdd_RestoreWorkFolder();
  FIS_fwApplHdd_SaveWorkFolder();
  FIS_fwApplHdd_SelectFolder();
  FIS_fwApplHdd_SetWorkFolder();
  FIS_fwApplTap_GetEmptyTask();
  FIS_fwApplTimer_OptimizeList();
  FIS_fwApplTimeToLocal();
  FIS_fwApplVfdSendData();
  FIS_fwApplVfdStart();
  FIS_fwApplVfdStop();
  FIS_fwDevEeprom_Info();
  FIS_fwDevFront_SetIlluminate();
  FIS_fwDevHdd_DeviceClose();
  FIS_fwDevHdd_DeviceOpen();
  FIS_fwEeprom_DirectWrite();
  FIS_fwPowerOff();
  FIS_fwSetIrCode();
  FIS_vAudioTrack();
  FIS_vBootReason();
  FIS_vCheckAutoDecTimerId();
  FIS_vcurTapTask();
  FIS_vEEPROM();
  FIS_vEEPROMPin();
  FIS_vEtcInfo();
  FIS_vfdTimerId();
  FIS_vFlash();
  FIS_vFlashBlockAutoDec();
  FIS_vFlashBlockDLNAData();
  FIS_vFlashBlockFavoriteGroup();
  FIS_vFlashBlockGameSaveData();
  FIS_vFlashBlockLanIPConfig();
  FIS_vFlashBlockNetwork();
  FIS_vFlashBlockNetworkUpdateConfig();
  FIS_vFlashBlockOTAInfo();
  FIS_vFlashBlockProviderInfo();
  FIS_vFlashBlockRadioServices();
  FIS_vFlashBlockSatInfo();
  FIS_vFlashBlockServerData();
  FIS_vFlashBlockServiceName();
  FIS_vFlashBlockTimeInfo();
  FIS_vFlashBlockTimer();
  FIS_vFlashBlockTransponderInfo();
  FIS_vFlashBlockTVServices();
  FIS_vgrid();
  FIS_vhddTapFolder();
  FIS_vhddTsFolder();
  FIS_viboxTimerId();
  FIS_vIsPipActive();
  FIS_vMACAddress();
  FIS_vnPipSvcNum();
  FIS_vOSDMap();
  FIS_vParentalInfo();
  FIS_vPipH();
  FIS_vPipSvcNum();
  FIS_vPipW();
  FIS_vPipX();
  FIS_vPipY();
  FIS_vRECSlotAddress(0);
  FIS_vShoutCastInfo();
  FIS_vShoutCastState();
  FIS_vTAPTable();
  FIS_vvfdBrightTimerId();
  FixInvalidFileName(NULL);
  FlashADDecode(NULL, NULL);
  FlashADDecode_ST_TMSC(NULL, NULL);
  FlashADDecode_ST_TMSS(NULL, NULL);
  FlashADDecode_ST_TMST(NULL, NULL);
  FlashADEncode(NULL, NULL);
  FlashADEncode_ST_TMSC(NULL, NULL);
  FlashADEncode_ST_TMSS(NULL, NULL);
  FlashADEncode_ST_TMST(NULL, NULL);
  FlashADGetInfo(NULL);
  FlashADSetInfo(NULL);
  FlashGetTrueLocalTime(0, 0);
  FlashSatTablesDecode(NULL, NULL);
  FlashSatTablesDecode_ST_TMSC(NULL, NULL);
  FlashSatTablesDecode_ST_TMSS(NULL, NULL);
  FlashSatTablesDecode_ST_TMST(NULL, NULL);
  FlashSatTablesGetInfo(0, NULL);
  FlashSatTablesGetTotal();
  FlashServiceAdd(0, NULL);
  FlashServiceDecode(NULL, NULL);
  FlashServiceDecode_ST_TMSC(NULL, NULL);
  FlashServiceDecode_ST_TMSS(NULL, NULL);
  FlashServiceDecode_ST_TMST(NULL, NULL);
  FlashServiceEncode(NULL, NULL);
  FlashServiceEncode_ST_TMSC(NULL, NULL);
  FlashServiceEncode_ST_TMSS(NULL, NULL);
  FlashServiceEncode_ST_TMST(NULL, NULL);
  FlashServiceFind(0, 0, 0, 0, NULL);
  FlashServiceGetInfo(0, 0, NULL);
  FlashServiceGetTotal(0);
  FlashServiceSetInfo(0, 0, NULL);
  FlashTimeDecode(NULL, NULL);
  FlashTimeDecode_ST_TMSC(NULL, NULL);
  FlashTimeDecode_ST_TMSS(NULL, NULL);
  FlashTimeDecode_ST_TMST(NULL, NULL);
  FlashTimeGetInfo(NULL);
  FlashTimerDecode(NULL, NULL);
  FlashTimerDecode_ST_TMSC(NULL, NULL);
  FlashTimerDecode_ST_TMSS(NULL, NULL);
  FlashTimerDecode_ST_TMST(NULL, NULL);
  FlashTimerEncode(NULL, NULL);
  FlashTimerGetInfo(0, NULL);
  FlashTransponderFindIndex(0, 0, 0);
  FlashTransponderTablesDecode(NULL, NULL);
  FlashTransponderTablesDecode_ST_TMSC(NULL, NULL);
  FlashTransponderTablesDecode_ST_TMSS(NULL, NULL);
  FlashTransponderTablesDecode_ST_TMST(NULL, NULL);
  FlashTransponderTablesGetInfo(0, 0, NULL);
  FlashTransponderTablesGetTotal(0);
  FlushCache(NULL, 0);
  FM_FreeFontFile(NULL);
  FM_GetStringHeight(NULL, NULL);
  FM_GetStringWidth(NULL, NULL);
  FM_GetStringWidthAndRestrict(NULL, NULL, 0, FALSE);
  FM_LoadFontFile(NULL, NULL);
  FM_PutString(word rgn, dword x, dword y, dword maxX, const char * str, dword fcolor, dword bcolor, NULL, byte bDot, byte align);
  free_memory(NULL);
  FreeOSDRegion(word Region);
  GetApplVer();
  GetBits(NULL, short n);
  GetC(NULL);
  GetCurrentEvent(int *curEvent);
  getDword(void *buffer, bool NeedsByteSwapping);
  GetEEPROMAddress();
  GetEEPROMPin();
  GetLine(char *data, bool strip);
  GetMacAddress();
  GetNextMatch(NULL);
  GetOSDMapAddress();
  GetOSDRegionHeight(word Region);
  GetOSDRegionWidth(word Region);
  GetPIPPosition(int *North, int *South, int *East, int *West);
  GetSysID();
  GetSystemType();
  GetToppyString(0);
  GetUptime();
  getWord(void *buffer, bool NeedsByteSwapping);
  Hash(short p, 0);
  HDD_AAM_Disable();
  HDD_AAM_Enable(byte AAMLevel);
  HDD_APM_Disable();
  HDD_APM_Enable(byte APMLevel);
  HDD_ChangeDir(char *Dir);
  HDD_DecodeRECHeader(NULL, NULL, 0);
  HDD_DecodeRECHeader_ST_C(NULL, NULL);
  HDD_DecodeRECHeader_ST_S(NULL, NULL);
  HDD_DecodeRECHeader_ST_T(NULL, NULL);
  HDD_DecodeRECHeader_ST_T5700(NULL, NULL);
  HDD_DecodeRECHeader_ST_TMSC(NULL, NULL);
  HDD_DecodeRECHeader_ST_TMSS(NULL, NULL);
  HDD_DecodeRECHeader_ST_TMST(NULL, NULL);
  HDD_DecodeRECHeader_ST_TUK(NULL, NULL);
  HDD_Delete(NULL);
  HDD_EncodeRECHeader(NULL, NULL, 0);
  HDD_EncodeRECHeader_ST_C(NULL, NULL);
  HDD_EncodeRECHeader_ST_S(NULL, NULL);
  HDD_EncodeRECHeader_ST_T(NULL, NULL);
  HDD_EncodeRECHeader_ST_T5700(NULL, NULL);
  HDD_EncodeRECHeader_ST_TMSC(NULL, NULL);
  HDD_EncodeRECHeader_ST_TMSS(NULL, NULL);
  HDD_EncodeRECHeader_ST_TMST(NULL, NULL);
  HDD_EncodeRECHeader_ST_TUK(NULL, NULL);
  HDD_FappendOpen(NULL);
  HDD_FappendWrite(TYPE_File *file, char *data);
  HDD_FindPCR(NULLBuffer, dword BufferSize, 0ID);
  HDD_GetAbsolutePathByTypeFile(TYPE_File *File, char *AbsFileName);
  HDD_GetFileSizeAndInode(char *Directory, NULL, dword *CInode, __off64_t *FileSize);
  HDD_GetFileTimeByAbsFileName(NULL);
  HDD_GetFileTimeByRelFileName(NULL);
  HDD_GetFileTimeByTypeFile(TYPE_File *File);
  HDD_GetHddID(char *ModelNo, char *SerialNo, char *FirmwareNo);
  HDD_GetInodeByAbsFileName(NULL);
  HDD_GetInodeByRelFileName(NULL);
  HDD_GetInodeByTypeFile(TYPE_File *File);
  HDD_IdentifyDevice(char *IdentifyDeviceBuffer);
  HDD_isAnyRecording();
  HDD_isCryptedStream(char *Buffer, dword BufferSize);
  HDD_isFileInUse(NULL);
  HDD_isRecording(byte RecSlot);
  HDD_MakeNewRecName(char *fname, word sequence);
  HDD_Move(NULL, char *FromDir, char *ToDir);
  HDD_NumberOfRECSlots();
  HDD_RecSlotDecode(0, tFlashTimer *RecSlot);
  HDD_RecSlotEncode(0, tFlashTimer *RecSlot);
  HDD_RECSlotSetDuration(0, word Duration);
  HDD_Recycle(NULL);
  HDD_RemoveDir(char *DirPath, bool Recursive);
  HDD_Rename(NULL, char *NewFileName);
  HDD_Smart_DisableAttributeAutoSave();
  HDD_Smart_DisableOperations();
  HDD_Smart_EnableAttributeAutoSave();
  HDD_Smart_EnableOperations();
  HDD_Smart_ReadData(word *DataBuf);
  HDD_Smart_ReadThresholdData(word *DataBuf);
  HDD_Smart_ReturnStatus();
  HDD_TAP_Callback(dword TAPID, void *ProcedureAddress, d0aram1, d0aram2, d0aram3, d0aram4);
  HDD_TAP_Disable(dword TAPID, bool DisableEvents);
  HDD_TAP_DisableAll(bool DisableEvents);
  HDD_TAP_DisabledEventHandler(word event, d0aram1, d0aram2);
  HDD_TAP_GetCurrentDir(char *CurrentDir);
  HDD_TAP_GetFileNameByIndex(int Index, char **TAPFileName);
  HDD_TAP_GetIDByFileName(char *TAPFileName);
  HDD_TAP_GetIDByIndex(int TAPIndex);
  HDD_TAP_GetIndexByID(dword TAPID);
  HDD_TAP_GetInfo(NULL, tTAPInfo *pTAPInfo);
  HDD_TAP_GetInfoByAbsPath(char *AbsFileName, tTAPInfo *pTAPInfo);
  HDD_TAP_GetStartParameter();
  HDD_TAP_isAnyRunning();
  HDD_TAP_isBatchMode();
  HDD_TAP_isDisabled(dword TAPID);
  HDD_TAP_isDisabledAll();
  HDD_TAP_isRunning(dword TAPID);
  HDD_TAP_PopDir();
  HDD_TAP_PushDir();
  HDD_TAP_SendEvent(dword TAPID, bool AllowParamInterception, word event, d0aram1, d0aram2);
  HDD_TAP_Start(char *TAPFileName, bool BatchMode, void* ParameterBlock, dword *TAPID);
  HDD_TAP_StartedByTAP();
  HDD_TAP_Terminate(dword TAPID);
  HDD_Unrecycle(NULL);
  HDD_Write(NULL, 0, TYPE_File *f);
  HookFirmware(char *FirmwareFunctionName, void *RedirectTo, dword *PointerToOriginal);
  INICloseFile();
  INIFindStartEnd(NULL, NULL, NULL, NULL);
  INIGetARGB(NULL, NULL, NULL, NULL, NULL, 0);
  INIGetARGB8(NULL, NULL, NULL, NULL, NULL, 0);
  INIGetHexByte(NULL, byte DefaultValue, byte MinValue, byte MaxValue);
  INIGetHexDWord(NULL, 0, dword MinValue, dword MaxValue);
  INIGetHexWord(NULL, word DefaultValue, word MinValue, word MaxValue);
  INIGetInt(NULL, long int DefaultValue, long int MinValue, long int MaxValue);
  INIGetRGB(NULL, NULL, NULL, NULL, 0);
  INIGetRGB8(NULL, NULL, NULL, NULL, 0);
  INIGetString(NULL, char *Value, char *DefaultValue, dword MaxLength);
  INIKeyExists(NULL);
  INIKillKey(NULL);
  INILocateFile(NULL, NULL);
  INIOpenFile(NULL, NULL);
  INISaveFile(NULL, 0, NULL);
  INISetARGB(NULL, 0, 0, 0, 0);
  INISetARGB8(NULL, 0, 0, 0, 0);
  INISetComment(NULL);
  INISetComment(NULLs);
  INISetHexByte(NULL, byte Value);
  INISetHexDWord(NULL, dword Value);
  INISetHexWord(NULL, word Value);
  INISetInt(NULL, long int Value);
  INISetRGB(NULL, 0, 0, 0);
  INISetRGB8(NULL, 0, 0, 0);
  INISetString(NULL, char *Value);
  InitGetBits(NULL);
  InitPutBits(NULL);
  InitSlide(NULL);
  InitTAPex();
  InitTAPexFailedMsg(char *ProgramName);
  InitVars(NULL);
  InsertNode(NULL);
  isAnyOSDVisible(dword checkX, dword checkY, dword checkW, dword checkH);
  isAnyOSDVisibleEx(dword checkX, dword checkY, dword checkW, dword checkH, byte Plane);
  isInfoBoxVisible();
  isLegalChar(unsigned char c, eRemoveChars ControlCharacters);
  iso639_1(int OSDLan);
  isOSDRegionAlive(word Region);
  isUTF8Char(NULL);
  isValidChannel(TAPCOM_Channel Channel);
  KeyTranslate(FALSE, void *EventHandler);
  KeyTranslateHook(word event, d0aram1, d0aram2);
  LangGetString(dword StringID);
  LangGetStringDefault(dword StringID, char *DefaultString);
  LangLoadStrings(char *LangFile, d0rStrings, int FallbackLang, NULL);
  LangUnloadStrings();
  LoadFirmwareDat(tFWDATHeader **FWDatHeader, tToppyInfo **ToppyInfo, tFWInfo **FWInfo);
  LogEntry(NULL, char *ProgramName, bool Console, eTimeStampFormat TimeStampFormat, NULL);
  LowerCase(char *string);
  make_crc_table();
  MakeChild(NULL, 0, 0, short r);
  MakeCode(short n, ARPByte len, ARPWord code, NULL);
  MakeLen(NULL, short root, NULL, byte *len, 0, ARPWord sortptr);
  MakeTable(NULL, short nchar, ARPByte bitlen, word tablebits, ARPWord table);
  MakeTree(NULL, 0, 0, byte *len, ARPWord codeparm);
  MakeUniqueFileName(NULL);
  MakeValidFileName(char *strName, eRemoveChars ControlCharacters);
  NoAutoStartTAP();
  Now(byte *Sec);
  OATH(register unsigned char * data, int len, dword hash);
  OSDCopy(word rgn, dword x, dword y, dword w, dword h, word items, eCopyDirection direction);
  OSDMemoInitialize(bool ScrollLoop, char *TitleLeft, char *TitleRight, NULL);
  OSDMenuButtonAdd(dword Line, tButtonIcon ButtonIcon, TYPE_GrData *ButtonGd, NULL);
  OSDMenuButtonsClear();
  OSDMenuColorPickerColor();
  OSDMenuColorPickerDestroy();
  OSDMenuColorPickerIsVisible();
  OSDMenuColorPickerShow(char *Title, dword DefaultColor);
  OSDMenuDestroy();
  OSDMenuEvent(word *event, dword *param1, dword *param2);
  OSDMenuGetCurrentItem();
  OSDMenuInfoBoxDestroy();
  OSDMenuInfoBoxIsVisible();
  OSDMenuInfoBoxShow(char *Title, NULL, dword Timeout);
  OSDMenuInitialize(bool AllowScrollingOfLongText, bool HasValueColumn, bool NumberedItems, bool ScrollLoop, char *TitleLeft, char *TitleRight);
  OSDMenuIsVisible();
  OSDMenuItemAdd(char *Name, char *Value, TYPE_GrData *pNameIconGd, TYPE_GrData *pValueIconGd, bool Selectable, bool ValueArrows, dword ID);
  OSDMenuItemGetCurrentID();
  OSDMenuItemGetCurrentName();
  OSDMenuItemGetCurrentValue();
  OSDMenuItemGetID(int ItemIndex);
  OSDMenuItemGetName(int ItemIndex);
  OSDMenuItemGetNrOfItems();
  OSDMenuItemGetValue(int ItemIndex);
  OSDMenuItemModifyColorPatch(int ItemIndex, 0);
  OSDMenuItemModifyName(int ItemIndex, NULL);
  OSDMenuItemModifyNameIcon(int ItemIndex, TYPE_GrData *pNameIconGd);
  OSDMenuItemModifySelectable(int ItemIndex, bool Selectable);
  OSDMenuItemModifyValue(int ItemIndex, NULL);
  OSDMenuItemModifyValueIcon(int ItemIndex, TYPE_GrData *pValueIconGd);
  OSDMenuItemModifyValueXPos(d0ewValueXPos);
  OSDMenuItemsClear();
  OSDMenuLogo(dword X, dword Y, TYPE_GrData *LogoGd);
  OSDMenuMessageBoxButtonAdd(NULL);
  OSDMenuMessageBoxButtonSelect(dword SelectedButton);
  OSDMenuMessageBoxDestroy();
  OSDMenuMessageBoxInitialize(char *Title, NULL);
  OSDMenuMessageBoxIsVisible();
  OSDMenuMessageBoxLastButton();
  OSDMenuMessageBoxShow();
  OSDMenuModifyItemLongTextScrolling(bool AllowScrollingOfLongText);
  OSDMenuModifyItemNumbered(bool NumberedItems);
  OSDMenuModifyItemValueColumn(bool HasValueColumn);
  OSDMenuModifyScrollLoop(bool ScrollLoop);
  OSDMenuModifyTitleLeft(NULL);
  OSDMenuModifyTitleRight(NULL);
  OSDMenuPop();
  OSDMenuProgressBarDestroy();
  OSDMenuProgressBarIsVisible();
  OSDMenuProgressBarShow(char *Title, NULL, dword Value, dword MaxValue, TYPE_GrData *DifferentProgressBar);
  OSDMenuPush();
  OSDMenuScrollDown();
  OSDMenuScrollEnd();
  OSDMenuScrollHome();
  OSDMenuScrollPageDown();
  OSDMenuScrollPageUp();
  OSDMenuScrollUp();
  OSDMenuSelectItem(int ItemIndex);
  OSDMenuUpdate(bool SuppressOSDSync);
  OSDToBMP(TYPE_OsdBaseInfo OsdBaseInfo, 0, 0, NULL, 0);
  ParseLine(char *zeile, size_t *n, char delim);
  PrintNet(char *puffer);
  Reboot(bool StopRecordings);
  RTrim(char *s);
  SaveBitmap(char *strName, 0, int height, byte* pBuffer );
  SendHDDCommand(dword Command, byte *CommandBlock, int BufferSize);
  SeparateFileNameComponents(NULL, char *Name, char *Ext, int *Index, bool *isRec, bool *isDel);
  SeparatePathComponents(char *FullName, char *Path, NULL, char *FileExt);
  setDword(void *buffer, dword Data, bool BigEndian);
  SetEEPROMPin(0ewPin);
  SetRemoteMode(byte Mode, bool Active);
  setWord(void *buffer, word Data, bool BigEndian);
  ShowMessageWin(char *title, char *lpMessage1, char *lpMessage2, dword dwDelay);
  ShowMessageWindow(char **content, d0os_x, d0os_y, byte fntSize, byte align, dword bdcolor, dword titlecolor, dword msgcolor, 0, dword delay);
  Shutdown(TaskEnum Task);
  SoundSinus(word freq, dword durationInMilliseconds, word Amplitude);
  stricstr(const char *s1, const char *s2);
  StringDBAdd(tStringDB *StringDB, NULL);
  StringDBCountRecords(tStringDB *StringDB);
  StringDBCurrent(tStringDB *StringDB);
  StringDBDel(tStringDB *StringDB);
  StringDBDestroy(tStringDB *StringDB);
  StringDBEOF(tStringDB *StringDB);
  StringDBFirst(tStringDB *StringDB);
  StringDBInit(tStringDB *StringDB, dword InitialSize);
  StringDBLoad(tStringDB *StringDB, NULL);
  StringDBNext(tStringDB *StringDB);
  StringDBPrev(tStringDB *StringDB);
  StringDBSave(tStringDB *StringDB, NULL);
  StringEndsWith(NULL, char *postfix);
  StrMkISO(byte *SourceString);
  StrMkUTF8(byte *SourceString);
  StrReplace(char *String, char *Find, char *Replace);
  StrToISO(byte *SourceString, byte *DestString);
  StrToUTF8(byte *SourceString, byte *DestString);
  SuperFastHash(register unsigned char * data, int len, dword hash);
  SwapDWords(NULLBuf);
  SwapWords(word *DataBuf);
  TAP_MemAlloc_Chk(NULL, 0);
  TAP_Osd_Copy_Chk(NULL, word srcRgnNum, word dstRgnNum, dword srcX, dword srcY, dword w, dword h, dword dstX, dword dstY, bool sprite);
  TAP_Osd_Create_Chk(NULL, dword x, dword y, dword w, dword h, byte lutIdx, int flag);
  TAP_Osd_FillBox_Chk(NULL, word rgn, dword x, dword y, dword w, dword h, 0);
  TAP_Osd_PutFreeColorGd(word rgn, int x, int y, TYPE_GrData * gd, bool sprite, dword FilterColor);
  TAP_Osd_PutFreeColorGd_Chk(NULL, word rgn, int x, int y, TYPE_GrData * gd, bool sprite, dword FilterColor);
  TAP_Osd_PutGd_Chk(NULL, word rgn, int x, int y, TYPE_GrData * gd, bool sprite);
  TAP_Osd_PutPixel_Chk(NULL, word rgn, dword x, dword y, d0ix);
  TAP_Osd_RestoreBox_Chk(NULL, word rgn, dword x, dword y, dword w, dword h, NULL);
  TAP_Osd_SaveBox_Chk(NULL, word rgn, dword x, dword y, dword w, dword h);
  TAPCOM_CloseChannel(TAPCOM_Channel Channel);
  TAPCOM_Finish(TAPCOM_Channel Channel, int val);
  TAPCOM_GetChannel(d0aram1, dword *CallerID, dword *ServiceID, dword *ParamBlockVersion, void **ParamBlock);
  TAPCOM_GetReturnValue(TAPCOM_Channel Channel);
  TAPCOM_GetStatus(TAPCOM_Channel Channel);
  TAPCOM_LastAlive(TAPCOM_Channel Channel);
  TAPCOM_OpenChannel(dword TargetID, d0, d0aramBlockVersion, void *ParamBlock);
  TAPCOM_Reject(TAPCOM_Channel Channel);
  TAPCOM_StillAlive(TAPCOM_Channel Channel);
  TF2UnixTime(dword TFTimeStamp);
  TFDSize(NULLTFD);
  TimeDiff(dword FromTime, dword ToTime);
  TimeFormat(0Time, byte Sec, eTimeStampFormat TimeStampFormat);
  TryResolve(char *Function);
  TunerGet(int MainSub);
  TunerSet(byte Tuner);
  UncompressBlock(NULL, 0, NULL, word outputsize);
  UncompressedFirmwareSize(NULLSrc);
  UncompressedLoaderSize(NULLSrc);
  UncompressedTFDSize(NULLSrc);
  UncompressFirmware(NULLSrc, NULLDest, NULL);
  UncompressLoader(NULLSrc, NULLDest, NULL);
  UncompressTFD(NULLSrc, NULLDest, NULL);
  UnhookFirmware(char *FirmwareFunctionName, void *RedirectTo, dword *PointerToOriginal);
  Unix2TFTime(dword UnixTimeStamp);
  UpperCase(char *string);
  UTCtoLocal(dword UTCTime);
  ValidFileName(char *strName, eRemoveChars ControlCharacters);
  VFD_CDAnimation(bool Forward);
  VFD_Clear();
  VFD_EnableCD(FALSE);
  VFD_EnableCDAnimation(FALSE);
  VFD_EnableHDD(FALSE);
  VFD_GetControl(bool GiveControl);
  VFD_isInUseByTAP();
  VFD_SetCDValue(int Percent);
  VFD_SetHDDValue(int Percent);
  VFD_SetIcon(tVFDIcon VFDIcon, bool On);
  VFD_SetLargeText(NULL);
  VFD_SetSmallText(NULL);
  VFD_Update();
  VideoToBMP(TYPE_VideoFrame VideoFrame, 0, 0, NULL, int DstX, int DstY, int DstWidth, int DstHeight);
  WriteCLen(NULL);
  WritePtLen(NULL, short n, short nbit, 0special);
  YUV2RGB( word yy, word uu, word vv, byte *r, byte *g, byte *b );
  YUV2RGB2( word yy, word uu, word vv, int *r, int *g, int *b );

  return 0;
}
