name: Build for TMS

on:
  push:
    branches: [ FBLib_MC, MergeIntoMC ]
  pull_request:
    branches: [ FBLib_MC, MergeIntoMC ]
  release:
    types: [ created ]

jobs:
  build:
    name: Build for Topfield TMS
    runs-on: ubuntu-latest

    steps:
    - name: Get the version
      id: get_version
      run: echo ::set-output name=version::${GITHUB_REF#refs/*/}

#    - name: Get latest release version number
#      id: get_version2
#      uses: battila7/get-version-action@v2

    - name: Checkout repository and submodules
      uses: actions/checkout@v2
#      with:
#        submodules: recursive

    - name: Compile code in container
      run: |
        docker run --rm -v ${{ github.workspace }}:/tap --env FBLib="" cwuensch/tmsbuild:FBLib "cd /tap && rm libFireBird.a && make"
        
    - name: Copy build artefact
      uses: actions/upload-artifact@v2
      with:
        name: libFireBird ${{ steps.get_version.outputs.version }}
        path: |
          ${{ github.workspace }}/libFireBird.h
          ${{ github.workspace }}/libFireBird.a

    - name: Upload release binaries
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          ${{ github.workspace }}/libFireBird.h
          ${{ github.workspace }}/libFireBird.a
